# Generated by Django 5.2.12 on 2026-03-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('wallet', 'Wallet'), ('documents', 'Documents'), ('bag', 'Bag'), ('keys', 'Keys'), ('accessories', 'Accessories'), ('others', 'Others')], max_length=20),
        ),
    ]
