# Generated by Django 5.2.12 on 2026-03-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_itemimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='items_images/'),
        ),
    ]
