# Generated by Django 5.2.12 on 2026-03-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_itemimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled')], default='pending', max_length=10),
        ),
    ]
